import Head from "next/head";
import Banner from "../components/banner";
import Client_logo from "../components/client_logo";
import DisplayView from "../components/display_view";
import SlideBanner from "../components/slide_banner";

import ProductImage from "../assets/img/GoldPhone-1-300x300 1.png";
import ProductImage3 from "../assets/img/prodcut6 1.png";
import ProductImage4 from "../assets/img/product-39 1.png";
import ProductImage2 from "../assets/img/widetv-300x300 1.png";

import ProductImage1 from "../assets/img/mobile.jpg";
import ProductImage21 from "../assets/img/mobile1.jpg";
import ProductImage31 from "../assets/img/radio1.jpg";
import ProductImage41 from "../assets/img/tv.jpeg";

export default function Home() {
  const topCategory = [
    {
      id: 1,
      title: "Mobile",
      image: ProductImage,
    },
    {
      id: 2,
      title: "TV",
      image: ProductImage2,
    },
    {
      id: 1,
      title: "Speaker",
      image: ProductImage3,
    },
    {
      id: 2,
      title: "wathch",
      image: ProductImage4,
    },
  ];

  const product1 = [
    {
      id: 1,
      image: ProductImage1,
      title: "Mobile",
      price: 5,
      disPrice: 8,
    },
    {
      id: 2,
      image: ProductImage31,
      title: "Radio",
      price: 8,
      disPrice: 10,
    },
    {
      id: 3,
      image: ProductImage41,
      title: "Tv",
      price: 6,
      disPrice: 9,
    },
    {
      id: 4,
      image: ProductImage21,
      title: "mobile",
      price: 3,
      disPrice: 6,
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SlideBanner />
        <DisplayView
          titleh="Category"
          heading_boldh="Top"
          heading_regularh="Categorys"
          cardType="categoryCard"
          datas={topCategory}
        />
        <Banner />
        <DisplayView
          titleh="Category"
          heading_boldh="Trending"
          heading_regularh="Product"
          cardType="productCard"
          datas={product1}
        />

        {/* <DisplayView
          titleh="Nest"
          heading_boldh="Best Selling"
          heading_regularh="Product"
          cardType="productCard"
          datas=""
        /> */}
        <Client_logo />
      </main>
    </div>
  );
}
